# version of docker-compose
version: '2.2'

# external network
networks:
  macvlan-network:
    external: true

# services (container)
services:
  ros-master:
    image: ur-ros-driver:lecture-week-05
    container_name: ros-master
    networks: 
      macvlan-network: 
        ipv4_address: 192.168.2.2
    environment:
      - "ROS_MASTER_URI=http://192.168.2.2:11311"
      - "ROS_HOSTNAME=192.168.2.2"
    command: stdbuf -o L roscore
    restart: always

  #ur10_cartesian_bringup
  #ur10_cartesian_passthrough_bringup
  ur-ros-driver:
    image: ur-ros-driver:lecture-week-05
    container_name: ur-ros-driver
    depends_on:
      - ros-master
    networks: 
      macvlan-network: 
        ipv4_address: 192.168.2.4
    environment:
      - "ROS_MASTER_URI=http://192.168.2.2:11311"
      - "ROS_HOSTNAME=192.168.2.4"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source ~/catkin_ws/devel/setup.bash &&
      roslaunch ur_robot_driver ur10_cartesian_passthrough_bringup.launch robot_ip:=192.168.2.63"
    cpus: 1.0
    privileged: true
    restart: always
  
  ur-ros-control:
    image: ur-ros-driver:lecture-week-05
    container_name: ur-ros-control
    depends_on:
      - ros-master
      - ur-ros-driver
    networks: 
      macvlan-network: 
        ipv4_address: 192.168.2.5
    environment:
      - "ROS_MASTER_URI=http://192.168.2.2:11311"
      - "ROS_HOSTNAME=192.168.2.5"
      - "DISPLAY=unix$DISPLAY" 
    volumes:
      - ~/eh_lecture/real/group_1/ur_ros_custom:/root/catkin_ws/src/ur_ros_custom
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
    command: tail -F anything
    cpus: 1.0
    privileged: true
    restart: always